openapi: 3.0.3
info:
  title: 学术直通车 API 文档
  version: 1.0.0
  description: API Document for Academic Express
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/user/avatar:
    post:
      operationId: upload_avatar
      description: 上传用户头像。
      tags:
      - v1
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
          description: 上传成功
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 参数错误
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 未登录
  /api/v1/user/change-password:
    post:
      operationId: change_password
      description: 修改密码。
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChangePassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChangePassword'
        required: true
      security:
      - jwtAuth: []
      responses:
        '204':
          description: 修改成功
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 参数错误
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 未登录
  /api/v1/user/login:
    post:
      operationId: v1_user_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/v1/user/login/refresh:
    post:
      operationId: v1_user_login_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/v1/user/login/verify:
    post:
      operationId: v1_user_login_verify_create
      description: |-
        Takes a token and indicates if it is valid.  This view provides no
        information about a token's fitness for a particular use.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenVerify'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenVerify'
          description: ''
  /api/v1/user/profile:
    get:
      operationId: get_current_user
      description: 获取当前登录用户信息。
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
          description: 获取成功
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 参数错误
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 未登录
    patch:
      operationId: edit_user_profile
      description: 更新当前登录用户信息。
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserDetail'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
          description: 修改成功
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 参数错误
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 未登录
  /api/v1/user/profile/{id}:
    get:
      operationId: get_user_by_id
      description: 获取用户信息。
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: 获取成功
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 用户不存在
  /api/v1/user/register:
    post:
      operationId: register
      description: 注册用户。
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
          description: 注册成功
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 参数错误
components:
  schemas:
    ChangePassword:
      type: object
      properties:
        old_password:
          type: string
        new_password:
          type: string
      required:
      - new_password
      - old_password
    Error:
      type: object
      properties:
        detail:
          type: string
        code:
          type: string
        fields:
          type: object
          additionalProperties: {}
      required:
      - code
      - detail
    PatchedUserDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        nickname:
          type: string
          title: 昵称
          maxLength: 255
        url:
          type: string
          format: uri
          title: 个人主页
          maxLength: 255
        avatar:
          type: string
          format: uri
          title: 头像
        scholar_url:
          type: string
          format: uri
          title: 学术主页
          maxLength: 255
        intro:
          type: string
          title: 个人简介
        view_count:
          type: integer
          readOnly: true
          title: 浏览次数
        date_joined:
          type: string
          format: date-time
          readOnly: true
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        phone:
          type: string
          title: 手机号
          maxLength: 32
        last_login:
          type: string
          format: date-time
          readOnly: true
          nullable: true
    Register:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          maxLength: 150
        password:
          type: string
          maxLength: 128
        nickname:
          type: string
          title: 昵称
          maxLength: 255
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        phone:
          type: string
          title: 手机号
          pattern: ^\d{10,11}$
          maxLength: 32
        url:
          type: string
          format: uri
          title: 个人主页
          maxLength: 255
      required:
      - email
      - nickname
      - password
      - phone
      - username
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    TokenVerify:
      type: object
      properties:
        token:
          type: string
          writeOnly: true
      required:
      - token
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        nickname:
          type: string
          title: 昵称
          maxLength: 255
        url:
          type: string
          format: uri
          title: 个人主页
          maxLength: 255
        avatar:
          type: string
          format: uri
          title: 头像
        scholar_url:
          type: string
          format: uri
          title: 学术主页
          maxLength: 255
        intro:
          type: string
          title: 个人简介
        view_count:
          type: integer
          readOnly: true
          title: 浏览次数
        date_joined:
          type: string
          format: date-time
          readOnly: true
      required:
      - date_joined
      - id
      - nickname
      - username
      - view_count
    UserDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        nickname:
          type: string
          title: 昵称
          maxLength: 255
        url:
          type: string
          format: uri
          title: 个人主页
          maxLength: 255
        avatar:
          type: string
          format: uri
          title: 头像
        scholar_url:
          type: string
          format: uri
          title: 学术主页
          maxLength: 255
        intro:
          type: string
          title: 个人简介
        view_count:
          type: integer
          readOnly: true
          title: 浏览次数
        date_joined:
          type: string
          format: date-time
          readOnly: true
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        phone:
          type: string
          title: 手机号
          maxLength: 32
        last_login:
          type: string
          format: date-time
          readOnly: true
          nullable: true
      required:
      - date_joined
      - id
      - last_login
      - nickname
      - phone
      - username
      - view_count
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
