# Generated by Django 4.2.5 on 2024-12-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pub', '0008_populate_arxiv_entry_authors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('arxiv_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pub.arxiventry')),
                ('github_repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pub.githubrepo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'histories',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
