# Generated by Django 5.1.2 on 2024-12-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-viewed_at'], 'verbose_name': '历史记录', 'verbose_name_plural': '历史记录'},
        ),
    ]
