# Generated by Django 4.2.5 on 2024-12-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_collection_collectiongroup_groupcollection_and_more'),
        ('user', '0005_collectiongithubrepo_collectionarxiventry_and_more'),
    ]

    operations = [
    ]
