# Generated by Django 4.2.5 on 2024-12-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20241206_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectiongithubrepo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectiongithubrepo',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectiongithubrepo',
            name='repo',
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='collection',
        ),
        migrations.DeleteModel(
            name='CollectionArxivEntry',
        ),
        migrations.DeleteModel(
            name='CollectionGithubRepo',
        ),
        migrations.DeleteModel(
            name='CollectionItem',
        ),
    ]
