# Generated by Django 5.1.2 on 2024-12-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_collectiongithubrepo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '收藏项目', 'verbose_name_plural': '收藏项目'},
        ),
        migrations.AlterModelOptions(
            name='collectiongroup',
            options={'verbose_name': '收藏分组', 'verbose_name_plural': '收藏分组'},
        ),
        migrations.AlterModelOptions(
            name='groupcollection',
            options={'verbose_name': '收藏分组项目', 'verbose_name_plural': '收藏分组项目'},
        ),
    ]
