# Generated by Django 5.1.2 on 2024-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArxivEntry',
            fields=[
                ('arxiv_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ArXiv ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('authors', models.JSONField(verbose_name='作者')),
                ('comment', models.TextField(blank=True, verbose_name='评论')),
                ('published', models.DateTimeField(verbose_name='发布时间')),
                ('updated', models.DateTimeField(verbose_name='更新时间')),
                ('primary_category', models.CharField(max_length=255, verbose_name='主要类别')),
                ('categories', models.JSONField(verbose_name='所有类别')),
                ('link', models.URLField(max_length=255, verbose_name='ArXiv 链接')),
                ('pdf', models.URLField(max_length=255, verbose_name='PDF 链接')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('citation_count', models.IntegerField(default=0, verbose_name='引用次数')),
            ],
            options={
                'verbose_name': 'ArXiv 论文',
                'verbose_name_plural': 'ArXiv 论文',
            },
        ),
    ]
