# Generated by Django 5.1.2 on 2024-11-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0002_githubrepo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='url',
            new_name='html_url',
        ),
        migrations.AlterField(
            model_name='arxiventry',
            name='comment',
            field=models.TextField(null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='description',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='homepage',
            field=models.URLField(max_length=255, null=True, verbose_name='主页'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='language',
            field=models.CharField(max_length=255, null=True, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='license',
            field=models.CharField(max_length=255, null=True, verbose_name='许可'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='readme',
            field=models.TextField(blank=True, null=True, verbose_name='README'),
        ),
    ]
