# Generated by Django 5.1.2 on 2024-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0003_rename_url_githubrepo_html_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepo',
            name='watchers_count',
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='subscribers_count',
            field=models.IntegerField(default=0, verbose_name='Watch 数量'),
        ),
    ]
