# Generated by Django 5.1.2 on 2024-11-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0004_remove_githubrepo_watchers_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArxivCategory',
            fields=[
                ('category_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='分类 ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name': 'ArXiv 分类',
                'verbose_name_plural': 'ArXiv 分类',
            },
        ),
    ]
