# Generated by Django 5.1.2 on 2024-11-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0006_arxiventry_synced_githubrepo_synced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArxivEntryAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='名')),
                ('middle_name', models.CharField(max_length=255, null=True, verbose_name='中间名')),
                ('last_name', models.CharField(max_length=255, verbose_name='姓')),
                ('affiliation', models.CharField(max_length=255, null=True, verbose_name='机构')),
                ('arxiv_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pub.arxiventry', verbose_name='ArXiv 论文')),
            ],
            options={
                'verbose_name': 'ArXiv 论文作者',
                'verbose_name_plural': 'ArXiv 论文作者',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='pub_arxiven_first_n_31f689_idx')],
            },
        ),
    ]
