# Generated by Django 4.2.5 on 2024-12-20 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pub', '0008_populate_arxiv_entry_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('arxiv', 'ArXiv Paper'), ('github', 'GitHub Repository')], max_length=10, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=255, verbose_name='资源 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源认领',
                'verbose_name_plural': '资源认领',
                'unique_together': {('user', 'resource_type', 'resource_id')},
            },
        ),
    ]
