name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Format check
      run: npm run format:check
    - name: Lint with ESLint
      run: npm run lint:check
    - name: Build project
      run: npm run build
    - name: Run unit tests
      run: npm run test:unit
    # - name: Run E2E tests
    #   run: |
    #     npx playwright install --with-deps
    #     npm run test:e2e
    # - uses: actions/upload-artifact@v2
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
